_pdf_index:
  pattern: /
  defaults: { _controller: PsPdfBundle:Example:index }

_pdf_using_facade_directly:
  pattern: /manually
  defaults: { _controller: PsPdfBundle:Example:usingFacadeDirectly }
  
_pdf_using_automatic_format_detection:
  pattern: /auto/{name}.{_format}
  defaults: { _controller: PsPdfBundle:Example:usingAutomaticFormatGuessing, _format: html }
  requirements:
    _format: html|pdf