language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.2
  - 7.1

env:
  - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit

jobs:
  include:
    - stage: Test
      php: 7.1
      name: prefer-lowest
      env:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
      install:
        - composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
    - stage: Test coverage
      script: phpdbg -qrr vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --coverage-text
      after_success:
        - php vendor/bin/php-coveralls -v
