language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.2
  - 7.1

before_install:
  - composer self-update
  - composer require --no-update symfony/framework-bundle "$SYMFONY_VERSION"

install:
  - composer install --prefer-dist --no-interaction --prefer-stable

script: vendor/bin/phpunit --configuration Tests/phpunit.xml

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

jobs:
  include:
    - stage: Test
      php: 7.1
      name: prefer-lowest
      install:
        - composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
