language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3
  - 7.2
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --prefer-stable

script: vendor/bin/phpunit --configuration Tests/phpunit.xml

jobs:
  include:
    - stage: Test
      php: 7.1
      name: prefer-lowest
      install:
        - composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
